name: Generate Ascii Repo

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6

            - name: List files
              run: ls -lrta

            - name: Executing Shell Script
              run: |
                chmod +x ascii-generate.sh
                ./ascii-generate.sh
            


            # - name: List files
            #   run: ls
            
            # - name: read files
            #   run: cat README.md