name: matrix-strategy

on: [push,workflow_dispatch]

jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest,ubuntu-20.04]
                images: [hello-world,alpine]
        runs-on: ${{matrix.os}}
        steps:
            - name: display docker version
              run: docker info
            - name: running on ${{matrix.os}}
              run: docker run ${{matrix.images}}
